name: 'Run test on Maxim Cloud'
description: 'Runs a test on Maxim Cloud using an API key.'

inputs:
  api-key:
    description: 'API key for Maxim Cloud'
    required: true

  ngrok-url:
    description: 'URL of ngrok tunnel'
    required: false

  repository:
    description: 'Repository name'
    required: false

  branch:
    description: 'Branch name'
    required: false

  pat:
    description: 'Personal access token'
    required: false

  replicas:
    description: 'Number of replicas'
    required: false

  start-file:
    description: 'Test start file'
    required: false

  directory:
    description: 'Directory the test is in'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'cpu'
  color: 'orange'
